import {calculate,period,signature,projection,horizonDate} from './model.mjs';
const $=id=>document.getElementById(id),money=v=>new Intl.NumberFormat('en-US',{style:'currency',currency:'USD',maximumFractionDigits:2}).format(v),pct=v=>`${v>=0?'+':''}${v.toFixed(2)}%`,esc=v=>String(v).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const stamp=timestamp=>Number.isFinite(timestamp)?new Intl.DateTimeFormat('en-US',{timeZone:'America/New_York',month:'short',day:'numeric',year:'numeric',hour:'numeric',minute:'2-digit',timeZoneName:'short'}).format(new Date(timestamp*1000)):'Timestamp unavailable';
let predictionSettings;
const colors=['#326650','#7fa68a','#ba995d','#486f94','#ac7971','#85739e','#869044','#488f96','#c88d58','#6f7c8d','#a66380'];
let state,prices,config,months=12,charts=[];let theme;try{theme=localStorage.getItem('theme');}catch{}document.documentElement.dataset.theme=theme|| (matchMedia('(prefers-color-scheme: dark)').matches?'dark':'light');
$('theme').onclick=()=>{document.documentElement.dataset.theme=document.documentElement.dataset.theme==='dark'?'light':'dark';try{localStorage.setItem('theme',document.documentElement.dataset.theme);}catch{}if(state)draw();};
async function get(path,json=true){const r=await fetch(path,{cache:'no-store'});if(!r.ok)throw Error(`${path} could not load (${r.status}).`);return json?r.json():r.text();}
function renderMarkdown(md){$('commentary').replaceChildren();let section=document.createElement('section');$('commentary').append(section);for(const block of md.trim().split(/\n\s*\n/)){if(/^#{1,3} /.test(block)){section=document.createElement('section');const h=document.createElement('h3');h.textContent=block.replace(/^#{1,3} /,'');section.append(h);$('commentary').append(section);}else if(block.startsWith('- ')){const ul=document.createElement('ul');block.split('\n').forEach(line=>{const li=document.createElement('li');li.textContent=line.replace(/^- /,'');ul.append(li);});section.append(ul);}else{const p=document.createElement('p');p.textContent=block;section.append(p);}}}
function holdings(){const query=$('search').value.toLowerCase();const rows=state.rows.filter(r=>`${r.ticker} ${r.name} ${r.sector}`.toLowerCase().includes(query));$('holdings').innerHTML=rows.map(r=>`<tr><td><strong>${esc(r.ticker)}</strong><small>${esc(r.name)}</small><small>${esc(r.sleeve)}</small></td><td>${esc(r.sector)}</td><td>${r.weight.toFixed(1)}% <span class="muted">/ ${r.target}%</span><div class="weight-track" aria-hidden="true"><span style="width:${r.weight}%"></span><i style="left:${r.target}%"></i></div></td><td>${money(r.price)}<small>${esc(stamp(prices.quotes[r.ticker].timestamp))}</small></td><td class="${r.return>=0?'positive':'negative'}">${pct(r.return)}</td><td>${esc(r.thesis)}<div class="risk-copy">Risk: ${esc(r.risk)}</div></td></tr>`).join('');$('search-status').textContent=rows.length?`${rows.length} of ${state.rows.length} holdings`:'No matching holdings.';}
function summary(){const s=state;$('value').textContent=money(s.total);$('day').textContent=`${s.total>=s.previous?'+':''}${money(s.total-s.previous)}`;$('day').className=s.total>=s.previous?'positive':'negative';$('day-detail').textContent=`${pct((s.total/s.previous-1)*100)} vs. provider previous closes*`;$('return').textContent=pct((s.total/s.cost-1)*100);$('return').className=s.total>=s.cost?'positive':'negative';$('count').textContent=s.rows.length;$('mix').textContent=`${s.core.toFixed(1)}% core / ${(100-s.core).toFixed(1)}% satellite`;
$('risk').innerHTML=[['Policy score',`${s.score} / 100`,'Simple checklist; not a risk forecast'],['Largest position',`${s.largest.weight.toFixed(1)}%`,`${s.largest.ticker} · stock cap excludes ETFs`],['Top equity sector',`${s.sectorMax.toFixed(1)}%`,'Estimated look-through · 25% ceiling'],['Drift alerts',s.drift.length,'More than 5 percentage points']].map(([a,b,c])=>`<div><p>${esc(a)}</p><strong>${esc(b)}</strong><small>${esc(c)}</small></div>`).join('');
const alerts=[...s.checks.filter(([,ok])=>!ok).map(([name])=>`Policy review: ${name}.`),...s.drift.map(r=>`${r.ticker}: ${r.drift.toFixed(1)} percentage points from target. Review contributions, costs and taxes before rebalancing.`)];$('alerts').innerHTML=alerts.length?alerts.map(a=>`<p class="alert warning">${esc(a)}</p>`).join(''):'<p class="alert">Within the modeled guardrails. ETF exposures are estimates; verify before acting.</p>';$('exposure-note').textContent=config.exposureNote;
$('allocation-legend').innerHTML=s.rows.map((r,i)=>`<span><i class="swatch" style="background:${colors[i%colors.length]}"></i>${esc(r.ticker)} <b>${r.weight.toFixed(1)}%</b></span>`).join('');holdings();}
function draw(){charts.forEach(c=>c.destroy());charts=[];const css=getComputedStyle(document.documentElement),ink=css.getPropertyValue('--muted').trim(),line=css.getPropertyValue('--line').trim(),green=css.getPropertyValue('--accent').trim();const data=period(prices.history,months);const validSignature=!prices.signature||prices.signature===signature(config);const series=validSignature?data:[];const exp=Object.entries($('exposure').value==='sector'?state.sectors:state.assets).sort((a,b)=>b[1]-a[1]);$('exposure-values').innerHTML=exp.map(([k,v])=>`<p>${esc(k)}: ${v.toFixed(2)}%</p>`).join('');
const label=prices.mode==='sample'?'SYNTHETIC DEMO — not actual or backtested returns.':'Observed prices only; no historical backfill.';
$('performance-note').textContent=!validSignature?'Holdings changed: run the updater to restart comparable performance history.':series.length<2?`${label} At least two observations are needed; history starts with the first successful update.`:`${label} Showing ${series[0].date} to ${series.at(-1).date}; ${pct((series.at(-1).portfolio/series[0].portfolio-1)*100)} portfolio, ${pct((series.at(-1).benchmark/series[0].benchmark-1)*100)} SPY. Indexed to 100 at the first available observation in the selected window. Dividends, fees and taxes excluded; shorter history is shown when the full period is unavailable.`;
if(!window.Chart){$('performance-note').textContent+=' Charts unavailable: cdnjs could not load. Holdings and exposure values remain available.';return;}
Chart.defaults.color=ink;Chart.defaults.font.family='system-ui';const base={responsive:true,maintainAspectRatio:false,animation:false,plugins:{legend:{display:false}}};charts.push(new Chart($('allocation'),{type:'doughnut',data:{labels:state.rows.map(r=>r.ticker),datasets:[{data:state.rows.map(r=>r.weight),backgroundColor:colors,borderWidth:2,borderColor:css.getPropertyValue('--surface').trim()}]},options:{...base,cutout:'74%',plugins:{legend:{display:false},tooltip:{callbacks:{label:c=>`${c.label}: ${c.raw.toFixed(1)}%`}}}}}));
charts.push(new Chart($('exposure-chart'),{type:'bar',data:{labels:exp.map(([k])=>k),datasets:[{data:exp.map(([,v])=>v),backgroundColor:green,borderRadius:3,barThickness:12}]},options:{...base,indexAxis:'y',scales:{x:{min:0,max:Math.max(25,Math.ceil(Math.max(...exp.map(([,v])=>v))/10)*10),grid:{color:line},ticks:{callback:v=>v+'%'}},y:{grid:{display:false},ticks:{font:{size:10}}}}}}));
charts.push(new Chart($('performance'),{type:'line',data:{labels:series.map(x=>x.date),datasets:[{label:'Portfolio',data:series.map(x=>x.portfolio/series[0].portfolio*100),borderColor:green,backgroundColor:green},{label:'S&P 500 proxy (SPY)',data:series.map(x=>x.benchmark/series[0].benchmark*100),borderColor:css.getPropertyValue('--gold').trim(),borderDash:[5,4]}].map(d=>({...d,pointRadius:0,borderWidth:2,tension:.15}))},options:{...base,interaction:{mode:'index',intersect:false},scales:{x:{grid:{display:false},ticks:{maxTicksLimit:7,maxRotation:0}},y:{grid:{color:line},ticks:{callback:v=>Number(v).toFixed(0)}}}}}));}
$('search').oninput=()=>state&&holdings();$('exposure').onchange=()=>state&&draw();$('periods').onclick=e=>{const b=e.target.closest('button');if(!b)return;months=Number(b.dataset.months);$('periods').querySelectorAll('button').forEach(x=>x.setAttribute('aria-pressed',String(x===b)));if(state)draw();};
get('commentary.md',false).then(renderMarkdown).catch(()=>{$('commentary').textContent='Commentary unavailable. Check commentary.md.';});
try{[config,prices]=await Promise.all([get('holdings.json'),get('prices.json')]);state=calculate(config,prices);const stale=Date.now()-Date.parse(prices.asOf)>5*86400000;$('status').textContent=prices.mode==='sample'?'ILLUSTRATIVE SAMPLE · All prices, balances and performance are fictional. Connect the updater for real quotes.':`PRICE SNAPSHOT · ${stamp(Date.parse(prices.asOf)/1000)} · ${prices.source}. ${prices.snapshotNote||"Saved market quotes; not streaming prices."} ${stale?'STALE DATA — check the Actions workflow.':'See each holding’s last-trade timestamp.'} ${prices.basis==='sample'?'Shares and cost bases are still sample inputs; replace them in holdings.json.':''}`;summary();draw();get('predictions.json').then(settings=>{predictionSettings=settings;$('growth').value=settings.annualGrowthPercent;$('spread').value=settings.annualRangePercent;$('prediction-assumptions').textContent=settings.description;renderPredictions();}).catch(()=>{$('prediction-note').textContent='Price scenarios unavailable: check predictions.json.';});}catch(e){$('status').textContent=`Unable to load portfolio: ${e.message} Serve the folder over HTTP; check both JSON files.`;$('status').setAttribute('role','alert');}

function renderPredictions(){
 if(!state||!predictionSettings)return;
 const growth=Number($('growth').value),spread=Number($('spread').value);
 try{
 if(!$('growth').value.trim()||!$('spread').value.trim())throw Error('Enter both assumptions to calculate scenarios.');
 projection(100,1,growth,spread);
 const horizons=[{label:"2 weeks",period:14,unit:"days",date:horizonDate(prices.quoteDate,0,14)},...[1,3,6].map(m=>({label:`${m} month${m>1?"s":""}`,period:m,unit:"months",date:horizonDate(prices.quoteDate,m)}))];
 $('prediction-head').innerHTML='<tr><th scope="col">Stock</th><th scope="col">Starting price</th>'+horizons.map(h=>`<th scope="col">${h.label}<small>${h.date}</small></th>`).join('')+'</tr>';
 $('predictions').innerHTML=state.rows.filter(r=>r.type==='Stock').map(r=>`<tr><td><strong>${esc(r.ticker)}</strong><small>${esc(r.name)}</small></td><td>${money(r.price)}<small>${esc(stamp(prices.quotes[r.ticker].timestamp))}</small></td>${horizons.map(h=>{const f=projection(r.price,h.period,growth,spread,h.unit);return `<td><strong>${money(f.base)}</strong><small>Base case · ${pct((f.base/r.price-1)*100)}</small><span class="forecast-range">${money(f.lower)} – ${money(f.upper)}</span><small>Downside – upside</small></td>`;}).join('')}</tr>`).join('');
 $('prediction-note').textContent=`Anchored to the ${prices.quoteDate} snapshot. Base growth assumption: ${growth}% per year; range parameter: ${spread}%. All values in USD. These inputs are assumptions, not a forecast based on company research.`;
 }catch(e){$('prediction-note').textContent=e.message;$('predictions').replaceChildren();}
}
for(const id of ['growth','spread'])$(id).addEventListener('input',renderPredictions);
$('reset-predictions').onclick=()=>{if(!predictionSettings)return;$('growth').value=predictionSettings.annualGrowthPercent;$('spread').value=predictionSettings.annualRangePercent;renderPredictions();};
