import test from 'node:test';import assert from 'node:assert/strict';import {readFile} from 'node:fs/promises';import {calculate,validate,period,projection,horizonDate} from '../model.mjs';import {snapshot,quote} from '../scripts/update-prices.mjs';
const c=JSON.parse(await readFile(new URL('./fixtures/holdings.json',import.meta.url))),p={mode:'sample',quotes:Object.fromEntries(c.holdings.map((h,i)=>[h.ticker,{price:[300,60,75,500,160,500,160,250,120,80,400][i],previousClose:[300,60,75,500,160,500,160,250,120,80,400][i]/1.0032,timestamp:1790884800}])),history:Array.from({length:1827},(_,i)=>({date:new Date(Date.UTC(2021,9,1)+i*86400000).toISOString().slice(0,10),portfolio:100+i*.02,benchmark:100+i*.03}))};
test('Sample has 11 holdings, 65% core, and obeys policy',()=>{const s=calculate(c,p);assert.equal(s.rows.length,11);assert.ok(Math.abs(s.total-100000)<.01);assert.ok(Math.abs(s.core-65)<.001);assert.equal(s.score,100);assert.equal(s.drift.length,0);assert.ok(Math.abs(Object.values(s.sectors).reduce((a,b)=>a+b)-100)<.001);});
test('Drift and stock concentration are measured from market values',()=>{const x=structuredClone(p);x.quotes.MSFT.price*=3;const s=calculate(c,x);assert.ok(s.drift.some(x=>x.ticker==='MSFT'));assert.equal(s.checks[3][1],false);});
test('Missing quotes and invalid targets fail explicitly',()=>{const x=structuredClone(p);delete x.quotes.BND;assert.throws(()=>calculate(c,x),/BND/);const y=structuredClone(c);y.holdings[0].target=36;assert.throws(()=>validate(y),/100/);});
test('Calendar period selection differs across 1M, 6M, 1Y, 5Y',()=>{const sizes=[1,6,12,60].map(m=>period(p.history,m).length);assert.ok(sizes.every((v,i)=>!i||v>sizes[i-1]));});
test('Live transition discards synthetic history; daily update deduplicates; changed shares reset',()=>{const qs=structuredClone(p.quotes);qs.SPY={price:600,previousClose:598,timestamp:qs.VTI.timestamp};let live=snapshot(c,p,qs);assert.equal(live.history.length,1);live=snapshot(c,live,qs);assert.equal(live.history.length,1);const next=structuredClone(qs);Object.values(next).forEach(q=>q.timestamp+=86400);live=snapshot(c,live,next);assert.equal(live.history.length,2);const changed=structuredClone(c);changed.holdings[0].shares++;assert.equal(snapshot(changed,live,next).history.length,1);});
test('Mixed market sessions rejected',()=>{const qs=structuredClone(p.quotes);qs.SPY={...qs.VTI,timestamp:qs.VTI.timestamp+86400};assert.throws(()=>snapshot(c,p,qs),/Mixed/);});
test('Quote parser uses header secret and preserves provider fields',async()=>{const q=await quote('TEST','secret',async(url,opts)=>{assert.ok(!url.includes('secret'));assert.equal(opts.headers['X-Finnhub-Token'],'secret');return {ok:true,json:async()=>({c:20,pc:19,t:Math.floor(Date.now()/1000)})};});assert.equal(q.price,20);assert.equal(q.previousClose,19);});

test('Price scenarios use disclosed assumptions and positive ordered ranges',()=>{for(const m of [1,3,6]){const f=projection(100,m,6,25);assert.ok(f.lower<f.base&&f.base<f.upper);assert.ok(f.lower>0);assert.ok(Math.abs(f.base-100*Math.pow(1.06,m/12))<1e-9);}assert.deepEqual(projection(100,6,0,0),{base:100,lower:100,upper:100});assert.throws(()=>projection(100,1,-100,25));assert.throws(()=>projection(100,1,6,NaN));});
test('Forecast horizons keep calendar dates and clamp month ends',()=>{assert.equal(horizonDate('2026-10-02',1),'2026-11-02');assert.equal(horizonDate('2026-10-02',3),'2027-01-02');assert.equal(horizonDate('2026-10-02',6),'2027-04-02');assert.equal(horizonDate('2027-01-31',1),'2027-02-28');});

test('Two-week outlook uses 14 calendar days and a 365-day year',()=>{assert.equal(horizonDate('2026-10-02',0,14),'2026-10-16');assert.equal(horizonDate('2026-12-25',0,14),'2027-01-08');const f=projection(100,14,6,25,'days');assert.ok(Math.abs(f.base-100*Math.pow(1.06,14/365))<1e-9);assert.ok(f.lower<f.base&&f.base<f.upper);assert.ok(f.upper<projection(100,1,6,25).upper);});
